import http from "node:http";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { Readable } from "node:stream";
import {
  extractInstructionsFromSystem,
  mapResponsesOutputToAnthropicContent,
  toResponsesInput,
} from "./anthropic-responses.ts";
import {
  mapAnthropicToolChoiceToResponsesToolChoice,
  mapAnthropicToolsToResponsesTools,
} from "./tool-schema.ts";
import type { JsonObject } from "./types.ts";
import { trimOrNull } from "./runtime-config.ts";
import {
  type AuthState,
  buildUpstreamUrl,
  mergeRequestHeaders,
  rewriteRequestPath,
} from "./upstream.ts";

interface ChatgptProxyOptions {
  workspaceSummary?: string;
}

function writeSseEvent(
  res: http.ServerResponse,
  event: string,
  data: unknown,
): void {
  res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
}

function appendWorkspaceSummaryIfNeeded(
  parsed: JsonObject,
  filteredTools: Array<Record<string, unknown>>,
  workspaceSummary?: string,
): void {
  if (filteredTools.length > 0 || !workspaceSummary) return;
  const existing = typeof parsed.instructions === "string" ? parsed.instructions : "";
  parsed.instructions = `${existing}\n\nLocal workspace snapshot (autogenerated):\n${workspaceSummary}\n\nWhen asked about this folder/project, answer concretely and immediately from this snapshot.`.trim();
}

export function adaptAnthropicMessagesRequestForChatgpt(
  parsed: JsonObject,
  options: ChatgptProxyOptions,
): JsonObject {
  if (typeof parsed.instructions !== "string") {
    const instructions = extractInstructionsFromSystem(parsed.system);
    if (instructions) parsed.instructions = instructions;
  }

  parsed.input = toResponsesInput(parsed.messages);
  const mappedTools = mapAnthropicToolsToResponsesTools(parsed.tools);
  const filteredTools = mappedTools.filter(
    (tool) => String(tool.name || "").trim().toLowerCase() !== "toolsearch",
  );

  appendWorkspaceSummaryIfNeeded(parsed, filteredTools, options.workspaceSummary);
  parsed.tools = filteredTools.length > 0 ? filteredTools : undefined;

  const mappedChoice = mapAnthropicToolChoiceToResponsesToolChoice(
    parsed.tool_choice,
  );
  if (mappedChoice !== undefined) parsed.tool_choice = mappedChoice;
  else delete parsed.tool_choice;

  const effort = parsed.output_config?.effort ?? parsed.reasoning?.effort;
  if (typeof effort === "string" && effort) {
    parsed.reasoning = {
      ...(parsed.reasoning && typeof parsed.reasoning === "object"
        ? parsed.reasoning
        : {}),
      effort,
    };
  }

  delete parsed.messages;
  delete parsed.system;
  delete parsed.max_tokens;
  delete parsed.max_output_tokens;
  delete parsed.output_config;
  delete parsed.thinking;
  delete parsed.metadata;
  parsed.store = false;
  return parsed;
}

function parseSseEvents(
  buffered: string,
  handler: (eventName: string, data: any) => void,
): string {
  let boundary = buffered.indexOf("\n\n");
  while (boundary !== -1) {
    const rawEvent = buffered.slice(0, boundary);
    buffered = buffered.slice(boundary + 2);
    let eventName = "";
    let dataText = "";
    for (const line of rawEvent.split("\n")) {
      if (line.startsWith("event:")) eventName = line.slice(6).trim();
      else if (line.startsWith("data:")) dataText += line.slice(5).trim();
    }
    if (eventName && dataText) {
      try {
        handler(eventName, JSON.parse(dataText));
      } catch {
        /* skip malformed */
      }
    }
    boundary = buffered.indexOf("\n\n");
  }
  return buffered;
}

export async function proxyChatgptCodexResponsesAsAnthropic(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  requestPath: string,
  upstreamOrigin: URL,
  authState: AuthState,
  overrideBody: JsonObject,
): Promise<void> {
  const upstreamUrl = buildUpstreamUrl(
    upstreamOrigin,
    rewriteRequestPath(upstreamOrigin, requestPath),
  );
  const upstreamPayloadString = JSON.stringify({
    ...overrideBody,
    stream: true,
  });
  const headers = {
    ...mergeRequestHeaders(req, authState),
    "content-type": "application/json",
    "content-length": String(Buffer.byteLength(upstreamPayloadString)),
  };

  const upstreamResponse = await fetch(upstreamUrl, {
    method: "POST",
    headers,
    body: upstreamPayloadString,
  });

  if (upstreamResponse.status >= 400) {
    const errorText = await upstreamResponse.text();
    res.writeHead(upstreamResponse.status, {
      "content-type": "application/json",
    });
    res.end(errorText);
    return;
  }

  if (!upstreamResponse.body) {
    const body = JSON.stringify({
      type: "error",
      error: { type: "api_error", message: "empty stream body from upstream" },
    });
    res.writeHead(502, {
      "content-type": "application/json",
      "content-length": Buffer.byteLength(body),
    });
    res.end(body);
    return;
  }

  const streamRequested = overrideBody.stream !== false;
  const responseId = `msg_${Date.now().toString(16)}`;
  let model = String(overrideBody.model || "");
  let text = "";
  let parsedContent: Array<Record<string, unknown>> = [];
  let stopReason: "tool_use" | "end_turn" = "end_turn";
  let usageInputTokens = 0;
  let usageOutputTokens = 0;

  const decoder = new TextDecoder();
  let buffered = "";
  for await (const chunk of Readable.fromWeb(upstreamResponse.body as any)) {
    buffered = parseSseEvents(
      buffered + decoder.decode(chunk as Buffer, { stream: true }),
      (_eventName, parsed) => {
        if (parsed?.type === "response.created" && parsed?.response?.model) {
          model = String(parsed.response.model);
        }
        if (
          parsed?.type === "response.output_text.delta" &&
          typeof parsed.delta === "string"
        ) {
          text += parsed.delta;
        }
        if (parsed?.type === "response.completed") {
          usageInputTokens = Number(parsed?.response?.usage?.input_tokens || 0);
          usageOutputTokens = Number(parsed?.response?.usage?.output_tokens || 0);
          if (trimOrNull(parsed?.response?.model)) {
            model = parsed.response.model;
          }
          if (Array.isArray(parsed?.response?.output)) {
            const mapped = mapResponsesOutputToAnthropicContent(
              parsed.response.output,
            );
            parsedContent = mapped.content;
            stopReason = mapped.stopReason;
          }
        }
      },
    );
  }

  if (parsedContent.length === 0 && text.length > 0) {
    parsedContent = [{ type: "text", text }];
  }

  if (streamRequested) {
    res.writeHead(200, {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache",
      connection: "keep-alive",
    });
    writeSseEvent(res, "message_start", {
      type: "message_start",
      message: {
        id: responseId,
        type: "message",
        role: "assistant",
        model,
        content: [],
        stop_reason: null,
        stop_sequence: null,
        usage: { input_tokens: 0, output_tokens: 0 },
      },
    });

    for (let i = 0; i < parsedContent.length; i += 1) {
      const block = parsedContent[i];
      if (block.type === "text") {
        writeSseEvent(res, "content_block_start", {
          type: "content_block_start",
          index: i,
          content_block: { type: "text", text: "" },
        });
        writeSseEvent(res, "content_block_delta", {
          type: "content_block_delta",
          index: i,
          delta: { type: "text_delta", text: block.text || "" },
        });
        writeSseEvent(res, "content_block_stop", {
          type: "content_block_stop",
          index: i,
        });
      } else if (block.type === "tool_use") {
        writeSseEvent(res, "content_block_start", {
          type: "content_block_start",
          index: i,
          content_block: {
            type: "tool_use",
            id: block.id,
            name: block.name,
            input: {},
          },
        });
        writeSseEvent(res, "content_block_delta", {
          type: "content_block_delta",
          index: i,
          delta: {
            type: "input_json_delta",
            partial_json: JSON.stringify(block.input ?? {}),
          },
        });
        writeSseEvent(res, "content_block_stop", {
          type: "content_block_stop",
          index: i,
        });
      }
    }

    writeSseEvent(res, "message_delta", {
      type: "message_delta",
      delta: { stop_reason: stopReason, stop_sequence: null },
      usage: { output_tokens: usageOutputTokens },
    });
    writeSseEvent(res, "message_stop", { type: "message_stop" });
    res.end();
    return;
  }

  const body = JSON.stringify({
    id: responseId,
    type: "message",
    role: "assistant",
    model,
    content: parsedContent,
    stop_reason: stopReason,
    stop_sequence: null,
    usage: { input_tokens: usageInputTokens, output_tokens: usageOutputTokens },
  });
  res.writeHead(200, {
    "content-type": "application/json",
    "content-length": Buffer.byteLength(body),
  });
  res.end(body);
}

function persistRefreshedChatgptTokens(
  authPath: string,
  refreshed: { accessToken: string; idToken?: string; refreshToken?: string },
): void {
  try {
    const parsed = JSON.parse(
      existsSync(authPath) ? readFileSync(authPath, "utf8") : "{}",
    ) as Record<string, any>;
    if (!parsed.tokens || typeof parsed.tokens !== "object") parsed.tokens = {};
    parsed.tokens.access_token = refreshed.accessToken;
    if (trimOrNull(refreshed.idToken)) parsed.tokens.id_token = refreshed.idToken;
    if (trimOrNull(refreshed.refreshToken)) {
      parsed.tokens.refresh_token = refreshed.refreshToken;
    }
    parsed.last_refresh = new Date().toISOString();
    writeFileSync(authPath, `${JSON.stringify(parsed, null, 2)}\n`, "utf8");
  } catch {
    /* skip */
  }
}

export async function refreshChatgptBearerToken(
  authState: AuthState,
): Promise<string> {
  if (!authState.chatgptRefreshConfig) {
    throw new Error("chatgpt refresh config is missing");
  }
  if (authState.refreshInFlight) return authState.refreshInFlight;

  authState.refreshInFlight = (async () => {
    const cfg = authState.chatgptRefreshConfig!;
    const response = await fetch("https://auth.openai.com/oauth/token", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        grant_type: "refresh_token",
        refresh_token: cfg.refreshToken,
        client_id: cfg.clientId,
      }),
    });

    const text = await response.text();
    if (!response.ok) {
      throw new Error(`token refresh failed: ${response.status}: ${text.slice(0, 200)}`);
    }

    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch {
      throw new Error("token refresh returned non-JSON");
    }

    const accessToken = trimOrNull(parsed.access_token);
    const idToken = trimOrNull(parsed.id_token);
    const refreshToken = trimOrNull(parsed.refresh_token);

    const nextToken = accessToken || idToken;
    if (!nextToken) {
      throw new Error("refresh response missing access_token or id_token");
    }

    authState.bearerToken = nextToken;
    if (refreshToken) authState.chatgptRefreshConfig = { ...cfg, refreshToken };

    persistRefreshedChatgptTokens(cfg.authPath, {
      accessToken: accessToken || authState.bearerToken,
      idToken: idToken ?? undefined,
      refreshToken: refreshToken ?? undefined,
    });

    return authState.bearerToken;
  })().finally(() => {
    authState.refreshInFlight = undefined;
  });

  return authState.refreshInFlight;
}
